function res = ProductBigMatrix(h,v)
    % A function to compute the matrix-vector product A*u using the big 
    % matrix generated by 1-D FD matrices
    
    dimx = 1/h + 1;
    dimy = 2/h + 1;
    % v is of the size dimy * dimx
    
    v1D = reshape(v, 1, []);
    T = createTriDiagonalMatrix(dimy);
    S = eye(dimy);
    A = createBlockTriDiagonalMatrix(dimx, T, S);
    prod = A * v1D';
    res = reshape(prod',dimy,dimx);
    
end

function A = createTriDiagonalMatrix(n)
    % Create a tri-diagonal matrix of size n x n
    
    % Diagonal elements
    mainDiag = (-4) * ones(n, 1);
    
    % Off-diagonal elements
    offDiag = ones(n, 1);
    
    % Create the tri-diagonal matrix
    A = spdiags([offDiag, mainDiag, offDiag], [-1, 0, 1], n, n);
end

function B = createBlockTriDiagonalMatrix(numBlocks, T, S)
    % create a block tri-diagonal matrix

    % Create a block tri-diagonal matrix
    B = kron(eye(numBlocks), T) + kron(diag(ones(numBlocks-1, 1), -1), S) + kron(diag(ones(numBlocks-1, 1), 1), S);

end